In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt 
import seaborn as sns

In [2]:
true = pd.read_csv("True.csv")
fake = pd.read_csv("Fake.csv")

In [3]:
true.head(5)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [4]:
fake.head(5)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
true['label']= 1
fake['label']= 0

In [6]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [7]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [8]:
news = pd.concat([fake,true],axis=0)

In [9]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [10]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [11]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [12]:
news.shape

(44898, 5)

In [13]:
news = news.drop(['title', 'subject', 'date'],axis=1)

In [14]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [15]:
news.tail()

                                                    text  label
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

## reshuffling

In [16]:
news = news.sample(frac=1)

In [17]:
news.head()

                                                    text  label
2273   Cards Against Humanity has to be one of the be...      0
14561  Has our lawless President finally conceded tha...      0
3277   Former President George H. W. Bush can teach D...      0
18869  BEIRUT (Reuters) - The Iraqi Kurdish vote for ...      1
6713   A customer at a New Orleans Family Dollar stor...      0

In [18]:
 news.reset_index(inplace=True)

In [19]:
news.head()

   index                                               text  label
0   2273  Cards Against Humanity has to be one of the be...      0
1  14561  Has our lawless President finally conceded tha...      0
2   3277  Former President George H. W. Bush can teach D...      0
3  18869  BEIRUT (Reuters) - The Iraqi Kurdish vote for ...      1
4   6713  A customer at a New Orleans Family Dollar stor...      0

In [20]:
news.drop(['index'],axis= 1, inplace=True)

In [21]:
news.head()

                                                text  label
0  Cards Against Humanity has to be one of the be...      0
1  Has our lawless President finally conceded tha...      0
2  Former President George H. W. Bush can teach D...      0
3  BEIRUT (Reuters) - The Iraqi Kurdish vote for ...      1
4  A customer at a New Orleans Family Dollar stor...      0

In [22]:
import re

In [23]:
def wordopt(text):
    #Covert into lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+','',text)
    #remove html tags
    text = re.sub(r'<.*?>','',text)
    #Remove punctuation
    text = re.sub(r'[^\w\s]','',text)
    #Remove digits
    text = re.sub(r'\d','',text)
    #remove newline characters
    text = re.sub(r'\n','',text)

    return text

In [24]:
news['text'] = news ['text'].apply(wordopt)

In [26]:
news['text']

0        cards against humanity has to be one of the be...
1        has our lawless president finally conceded tha...
2        former president george h w bush can teach don...
3        beirut reuters  the iraqi kurdish vote for ind...
4        a customer at a new orleans family dollar stor...
                               ...
44893    luanda reuters  angola s main opposition party...
44894    on friday donald trump canceled a rally in chi...
44895    washington reuters  youths who were brought to...
44896    how many times in one week can abc news publis...
44897    the new york daily news is not known for subtl...
Name: text, Length: 44898, dtype: object

In [27]:
x = news['text']
y = news['label']

In [28]:
x

0        cards against humanity has to be one of the be...
1        has our lawless president finally conceded tha...
2        former president george h w bush can teach don...
3        beirut reuters  the iraqi kurdish vote for ind...
4        a customer at a new orleans family dollar stor...
                               ...
44893    luanda reuters  angola s main opposition party...
44894    on friday donald trump canceled a rally in chi...
44895    washington reuters  youths who were brought to...
44896    how many times in one week can abc news publis...
44897    the new york daily news is not known for subtl...
Name: text, Length: 44898, dtype: object

In [29]:
y

0        0
1        0
2        0
3        1
4        0
        ..
44893    1
44894    0
44895    1
44896    0
44897    0
Name: label, Length: 44898, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

In [32]:
x_train.shape

(31428,)

In [33]:
x_test.shape

(13470,)

## feature extraction

In [34]:
from sklearn.feature_extraction.text import

ImportError: cannot import name 'TfidVectorizer' from 'sklearn.feature_extraction.text' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py)